"""16x16 pixel-art toolbar icons for the Excel 95 skin, in the old 16-colour palette.

render(key) takes the key a style.py icon was made with (("glyph", code, bar, fallback),
("text", ...), ("lines", kind)) and returns a 16x16 QPixmap, or None to keep the modern icon."""
from PySide6.QtCore import QRect, Qt
from PySide6.QtGui import QColor, QFont, QPainter, QPixmap

from . import style as S

PAL = {
    "k": "#000000", "w": "#FFFFFF", "g": "#808080", "s": "#C0C0C0", "y": "#FFFF00", "o": "#808000",
    "b": "#0000FF", "n": "#000080", "r": "#FF0000", "m": "#800000", "G": "#00FF00", "d": "#008000",
    "c": "#00FFFF", "t": "#008080", "p": "#800080", "P": "#FF00FF",
}

ART = {
    "new": """
        ................
        ..kkkkkkkk......
        ..kwwwwwwkk.....
        ..kwwwwwwkwk....
        ..kwwwwwwkkkk...
        ..kwwwwwwwwwk...
        ..kwwwwwwwwwk...
        ..kwwwwwwwwwk...
        ..kwwwwwwwwwk...
        ..kwwwwwwwwwk...
        ..kwwwwwwwwwk...
        ..kwwwwwwwwwk...
        ..kwwwwwwwwwk...
        ..kwwwwwwwwwk...
        ..kkkkkkkkkkk...
        ................""",
    "open": """
        ................
        ................
        .........kkk....
        ........k...k.k.
        .............kk.
        .kkk........kkk.
        kwyyk...........
        kyyykkkkkkk.....
        kyyyyyyyyyk.....
        kyyykkkkkkkkkk..
        kyykoooooooook..
        kykoooooooook...
        kkoooooooook....
        kkkkkkkkkkk.....
        ................
        ................""",
    "save": """
        ................
        .kkkkkkkkkkkkkk.
        .knkwwwwwwwwknk.
        .knkwwwwwwwwknk.
        .knkwwwwwwwwknk.
        .knkwwwwwwwwknk.
        .knkwwwwwwwwknk.
        .knnkkkkkkkknnk.
        .knnnnnnnnnnnnk.
        .knnkkkkkkkknnk.
        .knnksskssskknk.
        .knnksskssskknk.
        .knnksskssskknk.
        ..knkkkkkkkkknk.
        ...kkkkkkkkkkkk.
        ................""",
    "cut": """
        ................
        ....k.....k.....
        ....k.....k.....
        ....k.....k.....
        ....kk...kk.....
        .....k...k......
        .....kk.kk......
        ......kkk.......
        .......k........
        ......nkn.......
        ....nnn.nnn.....
        ...n..n.n..n....
        ...n..n.n..n....
        ...n..n.n..n....
        ....nn...nn.....
        ................""",
    "copy": """
        ................
        kkkkkk..........
        kwwwwkk.........
        kwggwkwk........
        kwwwwkkkk.......
        kwggggwwk.......
        kwwwkkkkkk......
        kwggkwwwwkk.....
        kwwwkwgggkwk....
        kwggkwwwwkkkk...
        kwwwkwggggggk...
        kkkkkwwwwwwwk...
        ....kwggggggk...
        ....kwwwwwwwk...
        ....kkkkkkkkk...
        ................""",
    "paste": """
        ................
        .....kkkkk......
        .kkkkswwwskkkk..
        .kooookkkkoook..
        .koooooooooook..
        .kooookkkkkkkkk.
        .kooookwwwwwwwk.
        .kooookwkkkkkwk.
        .kooookwwwwwwwk.
        .kooookwkkkkkwk.
        .kooookwwwwwwwk.
        .kooookwkkkkwwk.
        .kooookwwwwwwwk.
        .kkkkkkkkkkkkkk.
        ................
        ................""",
    "undo": """
        ................
        ................
        ................
        ...k............
        ..kk....kkk.....
        .knkkkkknnnkk...
        knnnnnnnnnnnnk..
        .knkkkkkkknnnk..
        ..kk......knnk..
        ...k.......knk..
        ..........knnk..
        .........knnk...
        ........knnk....
        ........kkk.....
        ................
        ................""",
    "find": """
        ................
        ................
        ..kkk....kkk....
        ..ksk....ksk....
        .kkkkk..kkkkk...
        .ksssk..ksssk...
        kkkkkkkkkkkkkk..
        kssskssssksssk..
        kssskk..kksssk..
        kssskk..kksssk..
        kwwwk....kwwwk..
        kwwwk....kwwwk..
        kkkkk....kkkkk..
        ................
        ................
        ................""",
    "fontcolor": """
        ................
        ......kk........
        .....kkkk.......
        .....k..k.......
        ....kk..kk......
        ....kkkkkk......
        ...kk....kk.....
        ...kk....kk.....
        ..kkkk..kkkk....
        ................
        ................
        ................
        ................
        ................
        ................
        ................""",
    "fill": """
        ................
        .....k..........
        ....k.k.........
        ...k.wwk........
        ..k.wwwwk.......
        .kwwwwwwwk......
        kwwwwwwwwwk.....
        .kwwwwwwwk.y....
        ..kwwwwwk..y....
        ...kwwwk...yy...
        ....kwk.....y...
        .....k..........
        ................
        ................
        ................
        ................""",
    "clear": """
        ................
        ................
        ................
        .......kkkkkk...
        ......krrrrrkk..
        .....krrrrrkrk..
        ....kwwwwwkrrk..
        ...kwwwwwkrrk...
        ..kwwwwwkrrk....
        .kkkkkkkkrk.....
        .kwwwwwkkk......
        .kkkkkkk........
        ................
        ................
        ................
        ................""",
    "zoomin": """
        ................
        ...kkkkk........
        ..kwwwwwk.......
        .kwwwkwwwk......
        .kwwwkwwwk......
        .kwkkkkkwk......
        .kwwwkwwwk......
        .kwwwkwwwk......
        ..kwwwwwkk......
        ...kkkkkkkk.....
        .........kkk....
        ..........kkk...
        ...........kk...
        ................
        ................
        ................""",
    "zoomout": """
        ................
        ...kkkkk........
        ..kwwwwwk.......
        .kwwwwwwwk......
        .kwwwwwwwk......
        .kwkkkkkwk......
        .kwwwwwwwk......
        .kwwwwwwwk......
        ..kwwwwwkk......
        ...kkkkkkkk.....
        .........kkk....
        ..........kkk...
        ...........kk...
        ................
        ................
        ................""",
    "add": """
        ................
        ..kkkkkkkk......
        ..kwwwwwwkk.....
        ..kwwwwwwkwk....
        ..kwwwwwwkkkk...
        ..kwwwwwwwwwk...
        ..kwwwwwwwwwk...
        ..kwwwwwwwwwk...
        ..kwwwwwwwwdd...
        ..kwwwwwwwwdd...
        ..kwwwwwwdddddd.
        ..kwwwwwwdddddd.
        ..kwwwwwwwwdd...
        ..kkkkkkkkkdd...
        ................
        ................""",
    "delete": """
        ................
        ................
        ..mm......mm....
        ..mrm....mrm....
        ...mrm..mrm.....
        ....mrmmrm......
        .....mrrm.......
        .....mrrm.......
        ....mrmmrm......
        ...mrm..mrm.....
        ..mrm....mrm....
        ..mm......mm....
        ................
        ................
        ................
        ................""",
    "brush": """
        ................
        ..kkkkkkkk......
        ..kyyyyyyk......
        ..kyyyyyyk......
        ..kkkkkkkk......
        ....kssk........
        ....kssk........
        .....kk.........
        .....kk.........
        .....kk.........
        ....kkkk........
        ....kmmk........
        ....kmmk........
        .....kk.........
        ................
        ................""",
    "filter": """
        ................
        ................
        .kkkkkkkkkkkkk..
        ..kwwwwwwwwwk...
        ...kwwwwwwwk....
        ....kwwwwwk.....
        .....kwwwk......
        ......kwk.......
        ......kwk.......
        ......kwk.......
        ......kwk.......
        ......kkk.......
        ................
        ................
        ................
        ................""",
    "wrap": """
        ................
        ................
        .kkkkkkkkkkk....
        ................
        .kkkkkkkkkkkk...
        ............k...
        ............k...
        .....k......k...
        ....kk......k...
        ...kkkkkkkkkk...
        ....kk..........
        .....k..........
        ................
        .kkkkkk.........
        ................
        ................""",
    "merge": """
        ................
        ................
        kkkkkkkkkkkkkkkk
        k..............k
        k..............k
        k..k........k..k
        k.kk...kk...kk.k
        kkkkkk.kk.kkkkkk
        k.kk..k..k..kk.k
        k..k..kkkk..k..k
        k.....k..k.....k
        k..............k
        kkkkkkkkkkkkkkkk
        ................
        ................
        ................""",
    "borders": """
        ................
        .kkkkkkkkkkkkkk.
        .k.....g.....k.
        .k.....g.....k.
        .k...........k.
        .k.....g.....k.
        .k.....g.....k.
        .kgg.gg.gg.ggk.
        .k.....g.....k.
        .k.....g.....k.
        .k...........k.
        .k.....g.....k.
        .k.....g.....k.
        .kkkkkkkkkkkkkk.
        ................
        ................""",
    "freeze": """
        ................
        .kkkkkkkkkkkkkk.
        .ksssnwwwwwwwwk.
        .ksssnwwwwwwwwk.
        .ksssnwwwwwwwwk.
        .nnnnnnnnnnnnnk.
        .ksssnwwwwwwwwk.
        .ksssnwwwwwwwwk.
        .ksssnwwwwwwwwk.
        .ksssnwwwwwwwwk.
        .ksssnwwwwwwwwk.
        .ksssnwwwwwwwwk.
        .kkkkkkkkkkkkkk.
        ................
        ................
        ................""",
    "insert_row": """
        ................
        .kkkkkkkkkkkkkk.
        .kwwwwwwwwwwwwk.
        .kwwwwwwwwwwwwk.
        .kkkkkkkkkkkkkk.
        .kyyyyyyyyyyyyk.
        .kyyyyyyyyyyyyk.
        .kkkkkkkkkkkkkk.
        .kwwwwwwwwwwwwk.
        .kwwwwwwwwwwwwk.
        .kkkkkkkkkkkkkk.
        .kwwwwwwwwwwwwk.
        .kwwwwwwwwwwwwk.
        .kkkkkkkkkkkkkk.
        ................
        ................""",
    "delete_row": """
        ................
        .kkkkkkkkkkkkkk.
        .kwwwwwwwwwwwwk.
        .kwwwwwwwwwwwwk.
        .kkkkkkkkkkkkkk.
        .kwmmwwwwwwmmwk.
        .kwwwmmmmmmwwwk.
        .kkkkkkkkkkkkkk.
        .kwwwmmmmmmwwwk.
        .kwmmwwwwwwmmwk.
        .kkkkkkkkkkkkkk.
        .kwwwwwwwwwwwwk.
        .kwwwwwwwwwwwwk.
        .kkkkkkkkkkkkkk.
        ................
        ................""",
    "sort_az": """
        ................
        ..k.........k...
        .k.k........k...
        .kkk........k...
        .k.k........k...
        ............k...
        .kkk........k...
        ...k........k...
        ..k.........k...
        .k........k.k.k.
        .kkk.......kkk..
        ............k...
        ................
        ................
        ................
        ................""",
    "sort_za": """
        ................
        .kkk........k...
        ...k........k...
        ..k.........k...
        .k..........k...
        .kkk........k...
        ............k...
        ..k.........k...
        .k.k........k...
        .kkk......k.k.k.
        .k.k.......kkk..
        ............k...
        ................
        ................
        ................
        ................""",
    "claude": """
        ................
        .......r........
        .......r........
        ..r....r....r...
        ...r...r...r....
        ....r..r..r.....
        .....r.r.r......
        ..rrrrrrrrrrr...
        .....r.r.r......
        ....r..r..r.....
        ...r...r...r....
        ..r....r....r...
        .......r........
        .......r........
        ................
        ................""",
}
ART["redo"] = "\n".join(line[::-1] for line in ART["undo"].strip("\n").splitlines())

GLYPHS = {S.G_NEW: "new", S.G_OPEN: "open", S.G_SAVE: "save", S.G_UNDO: "undo", S.G_REDO: "redo",
          S.G_CUT: "cut", S.G_COPY: "copy", S.G_PASTE: "paste", S.G_FIND: "find", S.G_FONTCOLOR: "fontcolor",
          S.G_FILL: "fill", S.G_CLEAR: "clear", S.G_ZOOMIN: "zoomin", S.G_ZOOMOUT: "zoomout", S.G_ADD: "add",
          S.G_DELETE: "delete", S.G_BRUSH: "brush"}
LINES = {"wrap", "merge", "borders", "freeze", "insert_row", "delete_row", "sort_az", "sort_za", "filter"}

_cache = {}


def _grid(name):
    rows = [r.strip() for r in ART[name].strip("\n").splitlines()]
    return [(r + "." * 16)[:16] for r in rows][:16]


def _from_art(name):
    pm = QPixmap(16, 16)
    pm.fill(Qt.transparent)
    p = QPainter(pm)
    for y, row in enumerate(_grid(name)):
        for x, ch in enumerate(row):
            if ch in PAL:
                p.fillRect(x, y, 1, 1, QColor(PAL[ch]))
    p.end()
    return pm


def _text(text, family="Times New Roman", px=14, bold=True, italic=False, underline=False, strike=False,
          color="#000000"):
    pm = QPixmap(16, 16)
    pm.fill(Qt.transparent)
    p = QPainter(pm)
    f = QFont(family)
    f.setPixelSize(px)
    f.setBold(bold)
    f.setItalic(italic)
    f.setUnderline(underline)
    f.setStrikeOut(strike)
    f.setStyleStrategy(QFont.NoAntialias)
    p.setFont(f)
    p.setPen(QColor(color))
    p.drawText(QRect(0, 0, 16, 16), Qt.AlignCenter, text)
    p.end()
    return pm


def _align(kind):
    """Black text lines like Office 95's alignment buttons."""
    pm = QPixmap(16, 16)
    pm.fill(Qt.transparent)
    p = QPainter(pm)
    black = QColor("#000000")
    if kind in ("left", "center", "right"):
        for i, ln in enumerate((14, 9, 14, 9, 14)):
            x = {"left": 1, "right": 15 - ln, "center": 1 + (14 - ln) // 2}[kind]
            p.fillRect(x, 2 + i * 3, ln, 1, black)
    else:  # top / middle / bottom
        p.setPen(QColor("#808080"))
        p.drawRect(1, 1, 13, 13)
        ys = {"top": (3, 5), "middle": (6, 8), "bottom": (10, 12)}[kind]
        for y in ys:
            p.fillRect(4, y, 8, 1, black)
    p.end()
    return pm


def _with_bar(pm, color):
    p = QPainter(pm)
    p.fillRect(1, 12, 14, 4, QColor(color))
    p.setPen(QColor("#808080"))
    p.drawRect(1, 12, 13, 3)
    p.end()
    return pm


def render(key):
    if key in _cache:
        return _cache[key]
    pm = _render(key)
    _cache[key] = pm
    return pm


def _render(key):
    kind = key[0]
    if kind == "glyph":
        _, code, bar, fallback = key
        name = GLYPHS.get(code)
        if name is None:
            return _text(fallback, "Arial", 12) if fallback else None
        pm = _from_art(name)
        return _with_bar(pm, bar) if bar else pm
    if kind == "lines":
        k = key[1]
        if k in ("left", "center", "right", "top", "middle", "bottom"):
            return _align(k)
        if k in ("dec_inc", "dec_dec"):
            return _text("+.0" if k == "dec_inc" else "-.0", "Arial", 10, bold=True)
        return _from_art(k) if k in LINES else None
    if kind == "text":
        _, text, bold, italic, underline, strike, color, bar = key
        if text == "✳":
            return _from_art("claude")
        if text in ("B", "I", "U"):
            pm = _text(text, "Times New Roman", 14, bold=True, italic=italic, underline=underline)
        elif text == "Σ":
            pm = _text("Σ", "Times New Roman", 15, bold=True)
        elif text == "fx":
            pm = _text("fx", "Times New Roman", 13, bold=False, italic=True)
        elif text == "ab":
            pm = _text("ab", "Arial", 11, bold=False, strike=True)
        else:
            pm = _text(text, "Arial", 13, bold=True)
        return _with_bar(pm, bar) if bar else pm
    return None
