"""Regenerate docs/excel-wishlist.md from sheets/ui/keytips.py (the single source of truth).

usage: python tools/make_wishlist.py
Includes how often each missing feature was tried, from %APPDATA%\\Sheets\\wishlist-tried.json."""
import datetime as dt
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from sheets.ui.keytips import GROUPS, KEYTIPS, load_tried  # noqa: E402

TAB = {"H": "Home", "A": "Data", "W": "View", "M": "Formulas", "N": "Insert", "R": "Review",
       "P": "Page Layout", "F": "File", "E": "Excel 2003 Edit", "O": "Excel 2003 Format",
       "I": "Excel 2003 Insert", "D": "Excel 2003 Data"}


def main():
    tried = load_tried()
    missing = [(seq, label, excel, tried.get(seq, {}).get("count", 0))
               for seq, label, action, excel in KEYTIPS if action is None]
    missing.sort(key=lambda r: (-r[3], r[0]))
    built = [(seq, label) for seq, label, action, _ in KEYTIPS if action is not None]
    out = [
        "# Excel features: wishlist and KeyTips",
        "",
        f"_Generated by `tools/make_wishlist.py` on {dt.date.today()} from `sheets/ui/keytips.py`. "
        "Edit the table there, then re-run the script._",
        "",
        "## Not built yet (wishlist)",
        "",
        "Pressing one of these KeyTips in Ekxel shows \"isn't in Ekxel yet\" and counts a try in "
        "`%APPDATA%\\Sheets\\wishlist-tried.json`. When working on Sheets, Claude asks the user about the "
        "most-tried items (see `CLAUDE.md`). To build one: implement it, give its KEYTIPS entry an action, "
        "re-run this script.",
        "",
        "| Tried | KeyTip | Feature | What it does in Excel | Status |",
        "| ---: | --- | --- | --- | --- |",
    ]
    for seq, label, excel, n in missing:
        out.append(f"| {n or ''} | Alt {' '.join(seq)} | {label} | {excel} | not built |")
    out += ["", "## Built KeyTips", "", "Press and release Alt, then type the letters "
            "(or hold Alt for the first letter). Esc steps back.", ""]
    current = None
    for seq, label in built:
        tab = TAB.get(seq[0], seq[0])
        if tab != current:
            out += ["", f"**{tab}**", ""]
            current = tab
        group = GROUPS.get(seq[:-1], "")
        out.append(f"- `Alt {' '.join(seq)}` {label}" + (f" ({group})" if group and len(seq) > 2 else ""))
    path = os.path.join(ROOT, "docs", "excel-wishlist.md")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")
    print(path, f"- {len(missing)} not built, {len(built)} built")


if __name__ == "__main__":
    main()
